version: "3"
services:
  db:
    image:  postgres
    restart: always 
    ports:
      - "5432:5432"
    environment:
       POSTGRES_PASSWORD: neverusedinproduction
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
        PGADMIN_DEFAULT_EMAIL: blackstag@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 8080
    ports:
        - 8080:8080
    links:
        - "db:pgsql-server"